# -*- coding: utf-8 -*-
#
# Author:: Matt Ray (<matt@chef.io>)
#
# Copyright:: 2018, Chef Software, Inc <legal@chef.io>
#

require 'yaml'

module Iggy
  class Profile
    # build a new InSpec profile
    # https://github.com/chef/inspec/tree/master/lib/bundles/inspec-init
    def self.render_profile(options, source_file, controls)
      name = options[:name]
      Dir.mkdir(name)
      Dir.mkdir("#{name}/controls")
      render_readme_md(name, source_file)
      render_inspec_yml(name, source_file, options)
      render_controls_rb(name, controls)
    end

    private

    def self.render_readme_md(name, file)
      f = File.new("#{name}/README.md", 'w')
      f.puts("# #{name}")
      f.puts
      f.puts("This profile was generated by InSpec-Iggy v#{Iggy::VERSION} from the #{file} source file.")
      f.close
    end

    def self.render_inspec_yml(name, file, options)
      yml = {}
      yml['name'] = name
      yml['title'] = options[:title]
      yml['maintainer'] = options[:maintainer]
      yml['copyright'] = options[:copyright]
      yml['copyright_email'] = options[:email]
      yml['license'] = options[:license]
      yml['summary'] = options[:summary]
      yml['version'] = options[:version]
      yml['description'] = "Generated by InSpec-Iggy v#{Iggy::VERSION} from the #{file} source file."
      f = File.new("#{name}/inspec.yml", 'w')
      f.write(yml.to_yaml)
      f.close
    end

    def self.render_controls_rb(name, controls)
      f = File.new("#{name}/controls/controls.rb", 'w')
      f.write(controls)
      f.close
    end
  end
end
